apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: event-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        version: blue
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: USER_SERVICE_URL
              value: "http://user-service:3001"
            - name: EVENT_SERVICE_URL
              value: "http://event-service:3002"
            - name: BOOKING_SERVICE_URL
              value: "http://booking-service:3003"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service:3004"
            - name: REDIS_URL
              value: "redis://redis-service:6379"
          livenessProbe:
            httpGet:
              path: /api/health/gateway
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health/gateway
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: event-booking
spec:
  selector:
    app: api-gateway
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
