apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: event-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: booking-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-service:5432/event_booking"
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: NATS_URL
              value: "nats://nats-service:4222"
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: event-booking
spec:
  selector:
    app: booking-service
  ports:
    - port: 3003
      targetPort: 3003
  type: ClusterIP
